<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>tool_cantam</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>tool-box.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="tool-box.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="MetadataExtractor" Version="2.9.3" />
  </ItemGroup>

</Project>
